APLIKASI = {
    "chrome": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "notepad": "C:\\Windows\\system32\\notepad.exe",
    "calculator": "C:\\Windows\\System32\\calc.exe",
    "word": "C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE",
    "excel": "C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE",
    "powerpoint": "C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE",
    "paint": "C:\\Windows\\system32\\mspaint.exe",
    "cmd": "C:\\Windows\\system32\\cmd.exe",
    "explorer": "C:\\Windows\\explorer.exe",
    "edge": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "outlook": "C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE",
    "onenote": "C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE",
    "snipping_tool": "C:\\Windows\\system32\\SnippingTool.exe",
    "task_manager": "C:\\Windows\\system32\\Taskmgr.exe",
    "wordpad": "C:\\Program Files\\Windows NT\\Accessories\\wordpad.exe",
    "vlc": "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "photoshop": "C:\\Program Files\\Adobe\\Adobe Photoshop 2023\\Photoshop.exe",
    "settings": "C:\\Windows\\ImmersiveControlPanel\\SystemSettings.exe",
    "powershell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "defender": "C:\\Program Files\\Windows Defender\\MSASCui.exe",
    "disk_cleaner": "C:\\Windows\\system32\\cleanmgr.exe",
    "remote_desktop": "C:\\Windows\\system32\\mstsc.exe",
    "regedit": "C:\\Windows\\regedit.exe",
    "device_manager": "C:\\Windows\\System32\\devmgmt.msc",
    "event_viewer": "C:\\Windows\\System32\\eventvwr.exe",
    "services": "C:\\Windows\\System32\\services.msc",
    "notepad_plus_plus": "C:\\Program Files\\Notepad++\\notepad++.exe",
    "winrar": "C:\\Program Files\\WinRAR\\WinRAR.exe",
    "zoom": "C:\\Users\\mbati\\AppData\\Roaming\\Zoom\\bin\\Zoom.exe",
    "teams": "C:\\Users\\mbati\\AppData\\Local\\Microsoft\\Teams\\Update.exe",
    "spotify": "C:\\Users\\mbati\\AppData\\Roaming\\Spotify\\Spotify.exe",
    "steam": "C:\\Program Files (x86)\\Steam\\Steam.exe",
}
